# Generated by Django 3.0.2 on 2020-01-10 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200110_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='topics',
        ),
        migrations.RemoveField(
            model_name='questions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='user',
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Questions',
        ),
        migrations.DeleteModel(
            name='UpVote',
        ),
    ]
